[package]
name = "boxdrawed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
fontdue = "0.8.0"
lazy_static = "1.4.0"
minifb = "0.25.0"
